\documentclass[11pt,a4paper]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

\usepackage[utf8]{inputenc}
%\usepackage[T1]{fontenc}
\usepackage[frenchb]{babel}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{threeparttable}
\usepackage[top=2cm,bottom=2cm,right=2cm,left=2cm]{geometry}

%\author{}
\title{Étude IRC à IgA 2010-2014}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\maketitle





La table "globale" contient 20455 patients différents pouvant avoir une IRCT avec maladie de Berger (1720), une néphropathie diabétique (11174), une glomérulonéphrite chronique (4417) ou une PKRD (3144).

La table "greffe" contient 1984 patients uniques (14 ont 2 patholgies), dont 958 (48.3\%) sont en commun avec la table "globale". 9 patients sont dans la table "greffe" alors qu'ils n'ont pas de date de greffe dans la table "globale".

\section{Incidence maladie de Berger}

On a 1720 patients qui ont eu une première suppléance. L'incidence était de 3.4 cas pour 100 000 habitants.

  \subsection{Incidence spatiale}

Tableau d'incidence selon la région par standardisation directe pour 100 000 habitants de 2010 à 2014 (selon l'effectif français de 2013) :
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
                           Ratio.brut Ratio.ajuste IC.inf IC.sup
Reunion                           5.7          5.8    3.9    8.8
Alsace                            5.4          5.5    4.3    6.8
Auvergne                          4.6          4.5    3.3    5.9
Nord.Pas.de.Calais                4.1          4.2    3.5    5.0
Bretagne                          4.0          3.9    3.2    4.7
Midi.Pyrénées                     3.8          3.8    3.0    4.6
Centre                            3.7          3.6    2.9    4.5
Champagne.Ardenne                 3.6          3.6    2.6    5.0
Pays.de.la.Loire                  3.7          3.6    3.0    4.4
Franche.Comté                     3.6          3.5    2.4    5.0
Rhône.Alpes                       3.5          3.5    3.0    4.1
Bourgogne                         3.6          3.4    2.5    4.5
Basse.Normandie                   3.3          3.2    2.3    4.4
Languedoc.Roussillon              3.2          3.2    2.5    4.1
Picardie                          3.0          2.9    2.1    3.9
Haute.Normandie                   2.8          2.8    2.0    3.8
Ile.de.France                     2.8          2.8    2.5    3.2
Aquitaine                         2.7          2.7    2.1    3.4
Lorraine                          2.7          2.7    2.0    3.6
Limousin                          2.6          2.6    1.5    4.4
Poitou.Charentes                  2.5          2.4    1.7    3.4
Provence.Alpes.Côte.d.Azur        2.4          2.3    1.9    2.8
Corse                             1.5          1.5    0.4    4.0
Guadeloupe                        1.0          1.0    0.2    3.4
Martinique                        0.7          0.7    0.1    3.0
\end{verbatim}
\end{kframe}
\end{knitrout}

  \subsection{Incidence temporelle}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

2010 2011 2012 2013 2014 <NA> 
 322  347  358  360  333    0 

2010 2011 2012 2013 2014 
18.7 20.2 20.8 20.9 19.4 

	Chi-squared test for given probabilities

data:  table(iga$anirt)
X-squared = 3.0988, df = 4, p-value = 0.5414
\end{verbatim}
\end{kframe}
\end{knitrout}

\section{Etude des caractéristiques cliniques et du devenir de ces patients}

  \subsection{Caractéristiques cliniques des patients au stade d’IRCT}
  
    \subsubsection{Age au stade d’IRCT (1ère suppléance) de 2010 à 2014 puis par années}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
[1] "2010-2014"
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  16.30   40.40   53.85   53.27   65.60   93.50 
[1] "Par année"
     Min. 1st Qu. Median  Mean 3rd Qu. Max.
2010 17.2   39.72  52.05 52.28   63.27 91.1
2011 16.3   36.90  54.20 51.74   65.25 90.0
2012 18.4   40.90  52.85 53.52   64.68 88.2
2013 19.4   40.90  55.45 54.59   67.03 90.3
2014 17.9   41.40  54.30 54.13   65.90 93.5
\end{verbatim}
\end{kframe}
\end{knitrout}

    \subsubsection{Taille, poids et BMI}
  
  Taille lors de l'IRCT :
  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  131.0   165.0   171.0   170.5   176.0   196.0     420 
\end{verbatim}
\end{kframe}
\end{knitrout}

Poids :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  11.50   63.50   72.00   74.01   83.00  164.00     294 
\end{verbatim}
\end{kframe}
\end{knitrout}

BMI :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

    <18.5 18.5-24.9   25-29.9   30-34.9   35-39.9       >40      <NA> 
       59       618       403       132        50        15       443 

    <18.5 18.5-24.9   25-29.9   30-34.9   35-39.9       >40 
      4.6      48.4      31.6      10.3       3.9       1.2 
\end{verbatim}
\end{kframe}
\end{knitrout}

      \subsubsection{Ponction Biopsie Rénale}

1199 (81.6\%) NA = 250

      \subsubsection{Co-morbidités}



Diabète : 193 (11.3\%) NA = 15

Type de diabète :
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

  1   2 
  9 179 

   1    2 
 4.8 95.2 
\end{verbatim}
\end{kframe}
\end{knitrout}

Cirrhose : 98 (6.5\%) NA = 208

Stade de la cirrhose :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

   0    1    2 <NA> 
1414   30   49  227 

   0    1    2 
94.7  2.0  3.3 
\end{verbatim}
\end{kframe}
\end{knitrout}

Insuffisance cardiaque : 149 (9.8\%) NA = 206

stade de l’IC :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

   0    1    2 <NA> 
1365   99   39  217 

   0    1    2 
90.8  6.6  2.6 
\end{verbatim}
\end{kframe}
\end{knitrout}

Infarctus du myocarde : 60 (4\%) NA = 207
~\\

Artériopathie des membres inférieurs : 112 (7.4\%) NA = 212
~\\

Stade de l’AOMI : 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

   0    1    2 <NA> 
1396   71   34  219 

   0    1    2 
93.0  4.7  2.3 
\end{verbatim}
\end{kframe}
\end{knitrout}

Amputation : 9 (0.6\%) NA = 247
~\\

Accident vasculaire cérébrale (AVC et AIT) :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
        iga$AITn
iga$AVCn    0    1 <NA>  Sum
    0    1418   15    6 1439
    1      39    8    1   48
    <NA>    2    0  231  233
    Sum  1459   23  238 1720
        iga$AITn
iga$AVCn    0    1
       0 95.8  1.0
       1  2.6  0.5
\end{verbatim}
\end{kframe}
\end{knitrout}

VIH : 13 (0.9\%)

Dont stade SIDA : 1 (7.7\%)
~\\

Ag HBS positif : 12 (0.8\%) NA = 217
~\\

PCR VHC positif : 11 (0.7\%) NA = 224


    \subsubsection{Statut Tabagique}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

       NF    Fumeur EX Fumeur      <NA> 
      755       243       327       395 

       NF    Fumeur EX Fumeur 
     57.0      18.3      24.7 
\end{verbatim}
\end{kframe}
\end{knitrout}

    \subsubsection{Créatinine, albumine et hémoglobine}

Créatininémie initiale :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   46.0   513.2   650.0   719.5   841.8  2793.0     526 
\end{verbatim}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-9-1} 

\end{knitrout}

Albuminémie initiale :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   9.00   30.00   34.60   34.05   38.60   58.00     707 
\end{verbatim}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-10-1} 

\end{knitrout}

Méthode de mesure de l'albumine initiale :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

       Automate  Electrophorèse              ND   Néphélémétrie 
            141              87              64             293 
Colorimétrique             <NA> 
            125            1010 

       Automate  Electrophorèse              ND   Néphélémétrie 
           19.9            12.3             9.0            41.3 
Colorimétrique  
           17.6 
\end{verbatim}
\end{kframe}
\end{knitrout}

Hémoglobine :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   4.70    9.10   10.30   10.26   11.40   17.60     400 
\end{verbatim}
\end{kframe}
\includegraphics[width=\maxwidth]{figure/unnamed-chunk-12-1} 

\end{knitrout}

Nombres d'anémiques :

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
       iga$gr_HBINI
iga$sex    1    0  Sum
    1    956   56 1012
    2    270   38  308
    Sum 1226   94 1320
       iga$gr_HBINI
iga$sex    1    0
      1 94.5  5.5
      2 87.7 12.3

	Pearson's Chi-squared test

data:  table(iga$sex, iga$gr_HBINI)
X-squared = 16.528, df = 1, p-value = 4.793e-05
\end{verbatim}
\end{kframe}
\end{knitrout}


    \subsubsection{Traitement de suppléance}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

        Hémodialyse Dialyse péritonéale              Greffe 
               1257                 296                 167 
               <NA> 
                  0 

        Hémodialyse Dialyse péritonéale              Greffe 
               73.1                17.2                 9.7 
\end{verbatim}
\end{kframe}
\end{knitrout}


    \subsubsection{Contexte de démarrage de dialyse}
    
Premier traitement en urgence :  322 (21.9\%) NA = 249
~\\

Premier traitement en réanimation :  85 (5.9\%) NA = 273

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
        iga$REAn
iga$URGn    0    1 <NA>
    0    1111   12   26
    1     233   71   18
    <NA>   18    2  229
\end{verbatim}
\end{kframe}
\end{knitrout}

Voie d’abord :
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

        FAV native Cathéter tunnélisé            Pontage 
               715                405                  7 
             Autre               <NA> 
                69                524 

        FAV native Cathéter tunnélisé            Pontage 
              59.8               33.9                0.6 
             Autre 
               5.8 
\end{verbatim}
\end{kframe}
\end{knitrout}

    \subsubsection{Activité}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}

                   <NA>                Retraité       Actif temps plein 
                    495                     458                     449 
          Inactif autre   Inactif en invalidité     Actif temps partiel 
                     69                      55                      48 
             Au chômage    Arrêt longue maladie                Au foyer 
                     46                      45                      32 
    Scolarisé, étudiant Actif en milieu protégé 
                     18                       5 

               Retraité       Actif temps plein           Inactif autre 
                   37.4                    36.7                     5.6 
  Inactif en invalidité     Actif temps partiel              Au chômage 
                    4.5                     3.9                     3.8 
   Arrêt longue maladie                Au foyer     Scolarisé, étudiant 
                    3.7                     2.6                     1.5 
Actif en milieu protégé 
                    0.4 
\end{verbatim}
\end{kframe}
\end{knitrout}

  \subsection{Devenir des patients après la mise en dialyse}
  
  \subsection{Analyse de la survie patient avec comme outcome le décès}
  
  On a 168 (9.8\%) patients qui sont décédés. On a al date de décès pour 238 (13.8\%) patients.
  
  \subsection{Recherche d’un lien entre les évènements infectieux saisonniers et la mise en route de la dialyse}
  
\section{Greffe}































\end{document}
